baseurl = "/"
languageCode = "en-us"
title = "Blog - Gitea"
theme = "gitea"
disableRSS = true
disableSitemap = true

[params]
  Description = "Git with a cup of tea"
  Author = "The Gitea Authors"
  Website = "https://blog.gitea.io"
