baseurl = "/"
languageCode = "en-us"
title = "Blog"
theme = "gitea"
disqusShortname = "gitea"
disableRSS = false
disableSitemap = false

defaultContentLanguage = "en"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[params]
  Description = "Git with a cup of tea"
  Author = "The Gitea Authors"
  Website = "https://blog.gitea.io"
  Toplink = "blog"

# [languages]
#   [languages.en]
#     weight = 0
#   [languages.de]
#     weight = 1
